[package]
name = "license-format"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek = { version = "2", features = ["rand_core"] }
flatbuffers.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
rand.workspace = true
